lista_frases=["eso es de cuando las ranas todavia tenian pelo",
    "siempre hay un roto para un descosido",
    "cagaste fuego hermano",
    "el que a hierro mata a hierro muere",
    "yo te bato la justa",
    "si te digo que la vaca es tuerta es porque ya tengo el ojo en la mano",
    "será jabón pero tiene gusto a queso",
    "vos tenés más problemas que los pérez garcía",
    "tenés menos estabilidad que un sachet de leche",
    "a vos no te gira la bandeja del microondas",
    "no te sube el agua al tanque",
    "no te salieron todos los parientes en la foto",
    "a vos te falta un buen golpe de horno",
    "te faltaron algunas lluvias de enero",
    "te faltan algunas monedas en el tarro",
    "pero vos no ves un burro a dos pasos",
    "deja de mover la jaula que se te marea la cotorra",
    "si te digo que es carnaval apreta el pomo",
    "el gato pierde el pelo pero no la maña",
    "hasta al mejor cazador se le escapa la liebre",
    "cómo será la laguna que el chancho la cruza al trote",
    "corto como patada de chancho",
    "por una teta no fue vaca",
    "cayó como peludo de regalo",
    "cada quien llora donde le aprieta el zapato",
    "cada quien hace de su culo un pito",
    "está más apretado que pedo de visita",
    "eso es harina de otro costal",
    "ya vas a volver con el caballo cansado",
    "la cabra al monte tira",
    "está para tirar manteca al techo",
    "como quien quiere la cosa",
    "te pasaste 3 pueblos vos",
    "viejo es el viento y todavía sopla",
    "eso es peligroso como cirujano con hipo",
    "estás denso como gárgara de dulce de leche",
    "estás más al pedo que oreja de sordo",
    "te pedí un tigre lamponne",
    "es más viejo que la escarapela",
    "es más viejo que andar a pie",
    "una paja más y te recibís de escoba",
    "escoba nueva siempre barre bien pero la vieja conoce los rincones",
    "es que no se le pueden pedir peras al olmo",
    "la manzana no cae muy lejos del árbol",
    "el que nace torta frita nunca llega a ser masa fina",
    "el que mucho abarca poco aprieta",
    "más sabe el diablo por viejo que por diablo",
    "dios los cria y el viento los amontona",
    "nunca hay que poner todos los huevos en una misma canasta",
    "por la plata baila el mono",
    "no hay que tocarle los bigotes al tigre",
    "me dejó más seca que pecera de mimbre",
    "menos averigua dios y perdona",
    "con el carro andando los melones se acomodan solos",
    "no es culpa del chancho, sino de quien lo alimenta",
    "cocodrilo que durmió es cartera",
    "entre gauchos no nos vamos a andar pisando el poncho",
    "entre fantasmas no nos vamos a pisar las sábanas",
    "a mamá mono con bananas verdes no",
    "ojo que no sea peor el remedio que la enfermedad",
    "fino como canapé de polenta",
    "lo que se arregla con plata sale barato",
    "agarró la sartén por el mango",
    "quieren inventar la polvora",
    "vos le debés una vela a cada santo",
    "eso es más peligroso que mono con navaja",
    "sos más papista que el papa",
    "al clavo salido siempre le toca el martillazo",
    "no podés ofrecer el oro y el moro",
    "a buen entendedor pocas palabras",
    "en casa de herrero cuchillo de palo",
    "a caballo regalado no se le miran los dientes",
    "cuando hay hambre no hay pan duro",
    "más agarrado que mugre de talón",
    "dios aprieta pero no ahoga",
    "nadie te dio vela en este entierro",
    "va de frente como canastito de bicicleta",
    "entre gitanos no nos vamos a andar leyendo las manos",
    "que tiene que ver el culo con la témpera",
    "se prendió como vizco al timbre",
    "si te gusta el durazno bancate la pelusa",
    "calavera no chilla",
    "están cayendo soretes de punta",
    "cuanto más podrido el pescado mas aplaude la foca",
    "el que tiene cola de paja que se haga un quincho",
    "https://twitter.com/jlespert/status/785601612303568896?lang=en", #Espert: quiero tetas
    "está mas fuerte que televisor de geriatrico",
    "está más fuerte que patada de allanamiento",
    "está mas fuerte que pis a la mañana",
    "está mas fuerte que cachetada de padrastro",
    "está para sacudirlo como termómetro de mercurio",
    "https://twitter.com/alferdez/status/939870090937462786?s=20", #Alberto: sos un imbecil fuera de lo común
    "el que se quema con leche ve la vaca y llora",
    "va para arriba como pedo de buzo",
    "sos más pesado que collar de sandias",
    "no puede ni decir oso al reves",
    "a vos te daban de tomar lavandina de chico?",
    "agarraste para el lado de los tomates",
    "se juntaron el hambre y las ganas de comer",
    "llueve sopa y vos con tenedor",
    "derrapaste un montón con eso",
    "dejá de mear afuera del tarro",
    "no te metas en camisa de 11 varas",
    "que te acomodas las medias si es foto carnet",
    "te agrandaste como sorete en kerosene",
    "que sabra el chancho de aviones",
    "no podés estar en la misa y en la procesión ",
    "ni tan calvo ni con peluca",
    "duró lo mismo que un pedo en una canasta",
    "estás más transpirada que monja con atraso ",
    "estás más transpirado que testigo falso",
    "desubicado como chupete en el culo",
    "que se yo, me pica el bagre"]

lista_sino=["claro rey",
    "me ves cara de saber?",
    "mmm vs decis negry",
    "por supollo",
    "ni de onda",
    "sospechá que no",
    "ni en pedo",
    "pa ke kieres saber eso jaja salu2",
    "https://www.youtube.com/watch?v=ZQLzkWACGjg", #afaerte
    "no lo c no zoi 100tifiko",
    "sospechá que sí",
    "pa que decirte que no si sí",
    "recontra remil sí",
    "recontra remil no",
    "claro que no",
    "no tengo ganas de contestarte la verdad",
    "claro que sí",
    "sorry bro, no",
    "https://www.youtube.com/watch?v=43zZJM5ecF4", #10 horas de vos sabes que sí
    "no, madre, no",
    "no lo veo muy probable eh",
    "well, yes but actually, yes",
    "ahí me mataste",
    "la verdad que ni idea",
    "que ganas de romperme las bolas por todo",
    "obvio kinga",
    "tampoco tengo la bola de cristal",
    "obvio que sí",
    "no salame",
    "sí master",
    "https://www.youtube.com/watch?v=fvtQYsckLxk", #My longest yeah boi ever
    "no capo no",
    "que se yo",
    "la respuesta está en tu corazón",
    "eso es algo que deberías preguntarte a vos mismo más seguido"]

lista_opiniones=["https://www.youtube.com/watch?v=rVda6oZwad8", #10 hours of absolute silence trap remix
    "me parece fantástico",
    "no me importa sinceramente",
    "el mejor invento del ser humano después de la rueda",
    "posta tengo que opinar?",
    "una re cagada",
    "es 1 poronga",
    "https://youtu.be/mDOcE54oaCY/", #Puta que vale la pena estar vivo
    "https://twitter.com/alferdez/status/939866625410465793?s=20", #Alberto: no discuto con boludos que se masturban
    "malardo",
    "malísimo",
    "una vez al año no hace daño",
    "plot twist: me chupa 1 huevo",
    "https://twitter.com/alferdez/status/1110729438092820482?s=20", #Alberto: Andamos muy bien hijo de puta
    "EU ME ENCANTA",
    "press F to pay respects",
    "https://www.youtube.com/watch?v=lvVDUF7cFzo", #yo le entro
    "F",
    "eee messi",
    "https://www.youtube.com/watch?v=yOnt4TRRnKs", #eee messi
    "no sabe no contesta",
    "no c. weno si c pero no te voy a decir",
    "excelente",
    "mooooooi bueno",
    "https://www.youtube.com/watch?v=yByKCPuDfFo", #10 horas de buenardo
    "fantabuloso"]

lista_piropos=["tantas curvas y yo sin frenos",
    "che tenés que ser más responsable con las fotos que subís hay bocha de gente con problemas en los pulmones por el virus y vos subiendo cosas que dejan sin aire a cualquiera",
    "estás para sacudirte como termómetro de mercurio",
    "te voy a empezar a cobrar alquiler por estar siempre en mis pensamientos bb",
    "ojalá fueras mi celular para manosearte todo el día",
    "no soy perro pero guau",
    "acompañame al registro civil así ponemos ese culo a mi nombre",
    "traé paraguas. no llueve, pero conmigo te vas a mojar",
    "de donde salió ese culo? de chernobyl? porque está monstruoso",
    "te quiero hacer la del delincuente que salta medianeras y entrarte por el fondo",
    "i love you te lo digo en inglés, ti amo te lo digo en italiano, pero que tenés alto caquero te lo digo en castellano",
    "no hace falta que hagas tanto ejercicio total corrés todos los días por mi mente",
    "no todos los tesoros son oro y plata, el mio sos vos en 4 patas",
    "no soy músico, pero si querés te enseño lo bien que se tocar",
    "si tuviese que elegir entre peras y manzanas, yo siempre elegiría tu banana",
    "cuando te veo casi me desmayo porque se me va toda la sangre a la pija",
    "estas para darte como a cajón que no cierra",
    "te quiero sacudir como desodorante vacío",
    "vos no serás el sol? porque me calentás un montón",
    "que ganas de ser parrilla para que me apoyes esa morcilla",
    "si me vas a dejar que sea sin ropa",
    "con ese culo cagame en el ojo y decime pirata de mierda",
    "si te alambrás el culo te compro una hectárea",
    "quisiera ser mariachi para tocarte todas las mañanas",
    "si el cuerpo es 70% agua significa que los nudes son agua y el agua no se le niega a nadie :)",
    "si me vas a clavar algo que no sea el visto",
    "a vos no te dejo en visto, a vos te desvisto",
    "con ese culo vení a cagar a casa",
    "estás más fuerte que mermelada de ajo",
    "si me invitás a tu cumpleaños te soplo la vela",
    "hablo tres idiomas, pero mi lengua favorita es la tuya",
    "no me digas tkm, que pienso que es te kiero manosear y me ilusiono",
    "debes ser basura, porque por vos mi cuerpo sufre un calentamiento global",
    "te invito a mi casa a jugar al uno, pero uno encima del otro",
    "quien pudiera ser jubilado para hacer esa cola",
    "como me gustaría ser bizco para mirarte dos veces",
    "que ganas de ser agua sucia para pasar por esa zanja",
    "si esa es la cola no me quiero imaginar el trámite",
    "con ese culo dedicame un pedo",
    "disfrazate de delivery y entregame la empanada",
    "con ese culo cualquiera gana el quini 6",
    "sos la rueda de auxilio de mi corazón sin llantas",
    "qué ganas de trabajar en una fábrica de telas para poner tela, sacar tela y acomodar tela todo el día",
    "estás más fuerte que patada de transformer",
    "tanto globo y yo sin fiesta?",
    "quiero ser las papas que acompañen ese lomo",
    "con esas gomas borrame el pasado",
    "voy a tener que llamar a sarmiento para que ponga un poco de civilización acá porque la verdad estás bárbara",
    "che por casualidad vos no sos sopa du macaco? porque sos uma delisia kkk",
    "me dejaste el virus porque la corona la tenés vos REINA",
    "si la gente fuera presa por ser linda vos tendrías perpetua",
    "disculpá, vos no sos la raíz de -1? porque no sos real",
    "como quisiera ser sol para darte todo el día"]

lista_gpt = []